version: 0.2
env:
  variables:
    key: "value"
    key: "value"
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/junkyard-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/stop_server.sh
    - scripts/start_server.sh
  discard-paths: no
